#
# Carsten Langgaard, carstenl@mips.com
# Copyright (C) 1999,2000 MIPS Technologies, Inc.  All rights reserved.
#
# Copyright (C) 2008 Wind River Systems, Inc.
#   written by Ralf Baechle <ralf@linux-mips.org>
#
obj-y				:= nvt-platform.o nvt-setup.o nvt-clk.o


# FIXME FIXME FIXME
#obj-$(CONFIG_MIPS_MT_SMTC)	+= nvt-smtc.o

