#
# Makefile for the gunzipManager routines.
#

obj-$(CONFIG_GZMANAGER) += gzmanager.o
gzmanager-objs := gzhost.o gzgzip.o
gzmanager-$(CONFIG_GZM_ZLIB) += gzzlib.o
#gzmanager-$(CONFIG_GZMANAGER_TEST) += gzmanager_test.o
